[package]
name = "AdventOfCode2025"
version = "0.1.0"
edition = "2024"

[dependencies]
rayon = "1.11.0"

[features]
simd = []

[profile.dev]
#opt-level = 3  # Belangrijk voor SIMD performance tijdens development
